# Generated by Django 6.0.2 on 2026-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('HOD', 'Head of Department'), ('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Lab Instructor', 'Lab Instructor')], default='Assistant Professor', max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=200)),
                ('student_name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('1st', '1st Place'), ('2nd', '2nd Place'), ('3rd', '3rd Place'), ('Participant', 'Participant'), ('Special Award', 'Special Award')], default='1st', max_length=20)),
                ('date', models.DateField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='winners/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
