# Generated by Django 4.2 on 2026-06-07 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentprofile',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
