# Generated by Django 6.0.2 on 2026-04-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_student_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Leave', 'Leave'), ('Absent', 'Absent')], max_length=10),
        ),
    ]
