# Generated by Django 5.2.6 on 2026-06-21 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0002_remove_parentprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='student',
            name='class_incharge',
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewer_role',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Superuser', 'Superuser')], max_length=20, null=True),
        ),
    ]
