# Generated by Django 5.2.6 on 2026-06-22 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0003_remove_leaverequest_class_incharge_reviewed_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mentor',
        ),
    ]
