# Generated by Django 6.0.2 on 2026-06-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_absentee_leaveattendance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='absentee',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='leaveattendance',
            unique_together={('student', 'date')},
        ),
        migrations.RemoveField(
            model_name='absentee',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='leaveattendance',
            name='subject',
        ),
    ]
