# Generated by Django 4.2 on 2026-04-22 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaulterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('staff_incharge', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('reason', models.TextField()),
                ('action_taken', models.CharField(blank=True, choices=[('letter', 'Letter'), ('letter_seminar', 'Letter + Seminar'), ('letter_assignment', 'Letter + Assignment')], max_length=30, null=True)),
            ],
        ),
    ]
