# Generated by Django 4.2 on 2026-05-08 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_defaulterstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='batch',
            field=models.CharField(default='2024-2028', max_length=20),
        ),
    ]
