# Generated by Django 5.2.6 on 2026-07-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0006_alter_absentee_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeupload',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='gradeupload',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gradeupload',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='grades/'),
        ),
    ]
