# Generated by Django 4.2 on 2026-05-29 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0009_student_mentor_alter_leaverequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_remark',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='mentor_remark',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='mentor_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='mentor_reviewed_by',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='from_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], db_index=True, default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='to_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('leave', 'Leave')], max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.CharField(db_index=True, default='2024-2028', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(help_text='Legacy field - do not use for new logic', max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
