# Generated by Django 4.2 on 2026-05-30 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0012_remove_subject_course_remove_subject_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='class_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ci_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
