# Generated by Django 4.2 on 2026-05-31 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0013_student_class_incharge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_remark',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='class_incharge_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='mentor_remark',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='mentor_reviewed_at',
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'subject', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together={('exam', 'student')},
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('marks', models.FloatField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='leave_app.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.student')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
