# Generated by Django 4.2 on 2026-06-02 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0014_remove_leaverequest_class_incharge_remark_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='reviewer_role',
            field=models.CharField(blank=True, choices=[('Mentor', 'Mentor'), ('Class Incharge', 'Class Incharge'), ('Superuser', 'Superuser')], max_length=20, null=True),
        ),
    ]
