# Generated by Django 4.2 on 2026-06-03 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leave_app', '0015_leaverequest_reviewed_at_leaverequest_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('semester', models.IntegerField()),
                ('uploaded_file', models.FileField(upload_to='grades/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=50)),
                ('subject_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grade', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave_app.student')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='leave_app.gradeupload')),
            ],
            options={
                'unique_together': {('upload', 'student', 'subject_code')},
            },
        ),
    ]
