# Generated by Django 4.2 on 2026-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0017_student_reg_no_alter_studentgrade_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='reg_no',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
