# Generated by Django 6.0.2 on 2026-06-06 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_app', '0018_alter_student_reg_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='circular',
            name='department',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='result',
            name='exam',
        ),
        migrations.AlterUniqueTogether(
            name='result',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='result',
            name='student',
        ),
        migrations.DeleteModel(
            name='AssignmentSubmission',
        ),
        migrations.DeleteModel(
            name='Circular',
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
