# Generated by Django 6.0.2 on 2026-06-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_brochure_alter_event_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='batch',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
