# Generated by Django 6.0.2 on 2026-06-11 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='brochure',
            field=models.FileField(default=1, upload_to='brochures/'),
            preserve_default=False,
        ),
    ]
