# Generated by Django 4.2 on 2026-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_brochure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='batch',
            field=models.CharField(choices=[('2024-2028', '2024-2028'), ('2025-2029', '2025-2029')], max_length=20),
        ),
    ]
